service: roland-garros-stats

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

  environment:
    dataAPI: "https://eurosportdigital.github.io/eurosport-node-developer-recruitment/headtohead.json"

functions:
  listPLayers:
    handler: server.listPlayers
    events:
      - http:
          path: /players
          method: get
          cors: false
  getPLayer:
    handler: server.getPlayer
    events:
      - http:
          path: /players/{playerId}
          method: get
          cors: false
